/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/example/emap': RouteRecordInfo<'/example/emap', '/example/emap', Record<never, never>, Record<never, never>>,
    '/example/marker': RouteRecordInfo<'/example/marker', '/example/marker', Record<never, never>, Record<never, never>>,
    '/example/markerclusterer': RouteRecordInfo<'/example/markerclusterer', '/example/markerclusterer', Record<never, never>, Record<never, never>>,
  }
}
